import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import clsx from "clsx";

import { ThemeProvider } from "@/components/theme-button";
import Navbar from "@/components/navbar";
import "./globals.css";

// todo: menambahkan local font
const nunito_sans = localFont({
  src: [
    {
      path: "./fonts/NunitoSans-ExtraBold.ttf",
      style: "normal",
      weight: "800",
    },
    { path: "./fonts/NunitoSans-Light.ttf", style: "normal", weight: "300" },
    { path: "./fonts/NunitoSans-SemiBold.ttf", style: "normal", weight: "600" },
  ],
  variable: "--font-nunito-sans",
  display: "swap",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <html lang='en'>
        <body
          className={clsx(
            nunito_sans.variable,
            "bg-vlg transition-all duration-100 font-nunito-sans",
            "dark:bg-vdb"
          )}
        >
          <div className='bg-white dark:bg-el-db shadow-md px-6'>
            <header className='max-w-[1200px] mx-auto'>
              <Navbar />
            </header>
          </div>
          <div className='px-6'>{children}</div>
        </body>
      </html>
    </ThemeProvider>
  );
}
